#ifndef CORE_MPISE_BUTTON_CODES
#define CORE_MPISE_BUTTON_CODES

#define AN_MOUSE_BUTTON_1      0
#define AN_MOUSE_BUTTON_2      1
#define AN_MOUSE_BUTTON_3      2
#define AN_MOUSE_BUTTON_4      3
#define AN_MOUSE_BUTTON_5      4
#define AN_MOUSE_BUTTON_6      5
#define AN_MOUSE_BUTTON_7      6
#define AN_MOUSE_BUTTON_8      7
#define AN_MOUSE_BUTTON_LAST   AN_MOUSE_BUTTON_8
#define AN_MOUSE_BUTTON_LEFT   AN_MOUSE_BUTTON_1
#define AN_MOUSE_BUTTON_RIGHT  AN_MOUSE_BUTTON_2
#define AN_MOUSE_BUTTON_MIDDLE AN_MOUSE_BUTTON_3

#endif // CORE_MPISE_BUTTON_CODES
